# Generated by Django 5.2 on 2025-04-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionanswer_delete_patientquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='user',
        ),
    ]
