# Generated by Django 5.2 on 2025-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionanswer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.JSONField(),
        ),
    ]
