# Generated by Django 5.2 on 2025-04-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_response_delete_questionanswer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='response',
            table='patient_questions',
        ),
    ]
