# Generated by Django 5.2 on 2025-04-26 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentavailability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointmentavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
