# Generated by Django 5.2 on 2025-04-26 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointmentavailability_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentavailability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
