# Generated by Django 5.2 on 2025-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointmentavailability_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentavailability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
