# Generated by Django 5.2 on 2025-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointmentavailability_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentavailability',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentavailability',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
