# Generated by Django 5.2 on 2025-04-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointmentavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentavailability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
