# Generated by Django 5.2 on 2025-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointmentavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentavailability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
